import RPi.GPIO as GPIO

PWM_DRIVE_LEFT = 21
FORWARD_LEFT_PIN = 26	
REVERSE_LEFT_PIN = 19	
PWM_DRIVE_RIGHT = 5		
FORWARD_RIGHT_PIN = 13
REVERSE_RIGHT_PIN = 6
GPIO.cleanup()
GPIO.setmode(GPIO.BCM)
GPIO.setup(PWM_DRIVE_LEFT, GPIO.OUT)
GPIO.setup(PWM_DRIVE_RIGHT, GPIO.OUT)
GPIO.setup(FORWARD_LEFT_PIN, GPIO.OUT)
GPIO.setup(REVERSE_LEFT_PIN, GPIO.OUT)
GPIO.setup(FORWARD_RIGHT_PIN, GPIO.OUT)
GPIO.setup(REVERSE_RIGHT_PIN, GPIO.OUT)

def allStop():
	GPIO.output(FORWARD_LEFT_PIN, GPIO.LOW)
	GPIO.output(REVERSE_LEFT_PIN, GPIO.LOW)
	GPIO.output(FORWARD_RIGHT_PIN, GPIO.LOW)
	GPIO.output(REVERSE_LEFT_PIN, GPIO.LOW)
def forwardDrive():
    GPIO.output(FORWARD_LEFT_PIN, GPIO.HIGH)
	GPIO.output(REVERSE_LEFT_PIN, GPIO.LOW)
	GPIO.output(FORWARD_RIGHT_PIN, GPIO.HIGH)
	GPIO.output(REVERSE_LEFT_PIN, GPIO.LOW)
def reverseDrive():
	GPIO.output(FORWARD_LEFT_PIN, GPIO.LOW)
	GPIO.output(REVERSE_LEFT_PIN, GPIO.HIGH)
	GPIO.output(FORWARD_RIGHT_PIN, GPIO.LOW)
	GPIO.output(REVERSE_LEFT_PIN, GPIO.HIGH)
def TurnLeft():
	GPIO.PWM(PWM_DRIVE_LEFT,1000)
	GPIO.PWM(PWM_DRIVE_RIGHT,100)
def TurnRight():
	GPIO.PWM(PWM_DRIVE_LEFT,100)
	GPIO.PWM(PWM_DRIVE_RIGHT,1000)
def center():
	GPIO.PWM(PWM_DRIVE_LEFT,1000)
	GPIO.PWM(PWM_DRIVE_RIGHT,1000)
